### PR TITLE
Adding windows build support

### PR DESCRIPTION
**Pull request by ldhertert**
This branch isn't really ready for being merged in yet, but I wanted to start the discussion of issues I ran into when trying to get this npm package installed on windows.

1. There is no windows distribution of open-zwave, so the paths in bindings.gyp are arbitrary. I ended up writing a sample script that will download the open-zwave code from github, build it and copy the required files to ./lib/open-zwave: https://gist.github.com/ldhertert/6a5597a93013da06044a
2. The open-zwave windows libraries produced by the default solution are 32 bit, which broke things for me because 64bit node will compile this module in 64 bit mode and throw errors due to discrepancies. This prompted me to create a fork than anyone could build with that enables a 64 bit target: https://github.com/ldhertert/open-zwave/tree/x64-support
3. The open-zwave windows libraries build for the Multi Threaded DLL runtime library, which is different than the node-gyp defualt.  I had to update the node-gyp accordingly.
4. I wasn't sure where to put the ozw files, since this is supposed to be a dynamically linked/shared dependency, but ozw doesn't have a standard installation path on windows, so I am assuming that they will be relative to the project (./lib/open-zwave).  If you'd like to see this handled differently, feel free to say so.
5. A couple c++ build fixes.  Note, **there is a potentially breaking change in .\src\openzwave.cc**.  I got
a compilation error and this fixed it, however I don't know enough about
c++ to know if what I did will cause problems.

Please let me know if you have any thoughts.

### CODE REVIEW

**Comment by ldhertert** [comment]
Progress report - I also needed to add the OPENZWAVE_ETC definition and the config files, as well as enable security, however I haven't pushed my changes up because I'm not able to get past connecting to my z-stick.  It keeps giving me a serial port error (5 - EIO - Input/Output error).  I don't know enough about c++/node native bindings/serial port communication to debug this.  Putting this on hold unless someone comes to the rescue.

**Comment by tilleul** [comment]
Hi ! Seems like you made it farther than I have so far (see issue #33 https://github.com/OpenZWave/node-openzwave-shared/issues/33) ... I'll see if your fork can help me a bit :-)

**Comment by ekarak** [comment]
Hi Luke,

I've had several compilation issues reported (mostly by OS/X users - but I've replicated this on Linux) with the way I'm scanning the existence of the new security-related calls in OpenZWave (see the usage of #ifdef OPENZWAVE_SECURITY macro in the code).
Previously I was searching for the existence of the ZWSecurity.h in the include paths, but this check seriously messes things up when users have first installed the current master of OZW, then installed an older version of OpenZWave. The header file is found, but the resulting node extension is unusable (as the security-related calls are simply not found by the loader). Thus, the only sane check I can do without resorting to GNU autoconf (*yucks*) is to check for the existence of this symbol in the libopenzwave.so library:

_ZN9OpenZWave7Manager7AddNodeEjb

This is the mangled string for one of the new security-related methods:

OpenZWave::Manager::AddNode(unsigned int, bool)

the following binding.gyp directive thus works for me on Linux, and I suppose it will work on MacOS too:

"OPENZWAVE_SECURITY=<!@(nm <(OZW_LIB_PATH)/libopenzwave.so | grep _ZN9OpenZWave7Manager7AddNodeEjb | wc -l)"

I need the Windows equivalent of this call, as this uses 'nm' which is not available in Windows. The Windows equivalent is 'dumpbin.exe':  https://msdn.microsoft.com/en-us/library/c1h23y6c%28v=vs.120%29.aspx

Can you try if this command works in Windows?

`dumpbin /symbols (OZW_HOME)/bin/OpenZWave.lib | find /c "_ZN9OpenZWave7Manager7AddNodeEjb"`

Thanks!

**Comment by ldhertert** [comment]
Hey Elias,

So we are running into the limitation of my c++ knowledge, so bear with me.  The first issue with what you're trying to do is that dumpbin is not going to be on the PATH of any users, as it is a part of the visual studio tools.  I think there's a way to get the location of the users visual studio tools via node_gyp config, however I'd have to look into that.  

Assuming that we do have a way to call dumpbin, I can only tell you what I'm seeing, because I don't know enough about c++ compilation/binaries.

The command as you put it didn't help, so I tried some of the suggestions [here](http://stackoverflow.com/a/31410521). Here are the outputs I get when running various commands from the visual studio command prompt (has the various utilities like dumpbin on the path):

* `dumpbin /symbols %OZW_HOME%/bin/OpenZWave.lib` - Pretty much nothing, just says File Type: Library
* `dumpbin /all /exports %OZW_HOME%\bin\openzwave.lib` - https://gist.githubusercontent.com/ldhertert/3dda39e9159a6d3bb598/raw/c221f7ad91e412b6b7ada581c91fc9b70577c070/dumpbin-all-exports
* Calling undname with the output from above - https://gist.githubusercontent.com/ldhertert/3dda39e9159a6d3bb598/raw/c221f7ad91e412b6b7ada581c91fc9b70577c070/dumpbin-undname

I couldn't find the string that you were looking for (or even just AddNodeEjb) no matter what I did, but maybe it has something to do with how we're compiling.  Or maybe I'm doing something wrong.

Anyway, piping the output using `command | fine /c "xyz"` correctly returns a single line output with the number of matches (0, 1, 2).

Let me know if you want me to try anything else.

Luke

**Pull request merged**
