### PR TITLE
Make node-openzwave-shared build on SmartOS

### PR DESCRIPTION
**Pull request by sjorge**
A patch recently landed that makes libopenzwave build on SmartOS, but looks like the node bindings need a bit of love too.

After these changes I can successfully build on SmartOS.

### CODE REVIEW

**Comment by sjorge** [comment]
Hmmm looks my methode of fixing it is deperecated (if I understand the failure correctly). Shame I guess this PR can be close then, as I spend about 3 weeks on trying to get this to compile and this was the only way I found to solve the errors about std::string not mapping to OZW::std::string which does not exist.

**Comment by sjorge** [comment]
Going over the log in more detail, those seem to be coming from node itself?

**Comment by sjorge** [comment]
OK I think I fixed that, lets see what travis-ci thinks.

**Comment by sjorge** [comment]
@bahamas10 maybe you can have a quick scan over it? This is working fine for me.

**Comment by sjorge** [comment]
I tested this succesfully with node-red-contrib-openzwave after pointing to my own git repo instead of the npm version. Everything is working fine.

**Comment by sjorge** [comment]
I've also testes this against https://github.com/robertsLando/Zwave2Mqtt and everything is working fine too. So I am now fairly confident in this change.

**Comment by ekarak** [comment]
Thank you so much!

**Pull request merged**
