### PR TITLE
Patch 5

### PR DESCRIPTION
**Pull request by tilleul**
tested on 2 different computers using node x86, this fix is needed. Will now test on node x64.

### CODE REVIEW

**Comment by tilleul** [comment]
It's needed on node x64 as well...

**Comment by tilleul** [comment]
ok although my modifications work the first time, they won't if the tempPath/ozwinstall folder already exist ... we should either check if it exists before trying to mkdir or delete all temp files once the script has been executed (which would be better IMHO)

**Comment by ldhertert** [comment]
@tilleul - 
1) I think this is actually exactly how I already had it, I must have messed up the code right before I pushed it up.  Sorry
2) The temp path really shouldn't exist, as it is concatenating random characters to a folder name.  That's why I don't check to see if we need to remove it.
3) The ozw install folder does get removed if it already exists.

**Comment by ldhertert** [comment]
Actually, I lied, this is how i had it before, and then i changed it to /{temp dir}/ozwinstall/{random folder name}.  I don't understand how you were running into issues with the folder already existing, nor how this would fix the issue.  Your changes were to:

1. Add a leading path delimiter (this wouldn't be necessary on my machine, what do you get when you run `node -p "require('os').tmpDir()"`? For me I get a path that already includes a trailing slash, so no leading slash would be required.  
2. Change the temp folder from `/{temp dir}/ozwinstall/{random string}` to `/{temp dir}/ozwinstall-{random string}`.  The call that I'm using to create the directory should not fail if `/{temp dir}/ozwinstall` already exists, just if the final leaf dir exists.

Sorry, just trying to understand what exactly was failing on your system.

Thanks.

**Comment by ldhertert** [comment]
Oh, nevermind.  I understand why it was breaking now.  I changed around the order of some things.  Your changes should fix it.  Good catch.

**Pull request merged**
