### PR TITLE
Add support for raw value types

### PR DESCRIPTION
**Pull request by mdave**
This PR adds support for setting/getting raw value types, as arise in (for example) the usercode command class values. These are translated to V8 buffer objects since this seems to be the best container in terms of storing byte messages.

### CODE REVIEW

**Comment by ekarak** [comment]
thanks

**Comment by spellicer** [comment]
Thanks for adding support for Raw. I had been just copying the string handler to Raw for supporting lock codes on my network. I'm having some trouble switching to the superior Buffer based Raw handling (it makes parsing and setting the codes a lot easier). When I pass in a buffer I get an assertion error:
`node: ../src/node_buffer.cc:180: char* node::Buffer::Data(v8::Local<v8::Value>): Assertion 'val->IsUint8Array()' failed.`

I'm not sure if I'm calling it correctly. I'm simply passing a Buffer object filled with integers as the 5th parameter of setValue.

**Comment by mdave** [comment]
Hmm, not having this issue myself, although I am not explicitly constructing a Buffer when calling `SetValue` but using one that has been created in `GetValue`. What code are you using to construct the buffer?

**Comment by spellicer** [comment]
Sorry turns, out it was my own fault. I was going through a couple serializations to json and didn't correctly reinstantiate the Buffer. A simple new Buffer(serializedarray) before passing to setValue worked fine. Setting codes on my locks works again.

**Comment by Vebryn** [comment]
Hello,

It seems interesting, is there some examples ?

Best regards.

**Comment by spellicer** [comment]
I'll try and get back into my code and get it. It's in typescript so I'll try and show both the typescript and the javascript.

**Pull request merged**
