### PR TITLE
Add support function WriteConfig (sava settings)

### PR DESCRIPTION
**Pull request by yybd**
Support function WriteConfig (save settings)

### CODE REVIEW

**Comment by ekarak** [comment]
Please remove the .DS_Store file from the commit, its irrelevant to the suggested change. 
Otherwise, I'm happy to merge the changes. Thanks!

**Comment by yybd** [comment]
removed the .DS_Store file

**Comment by ekarak** [comment]
I've merged your changes. Will try to release new version during the weekend. Many thanks!

**Comment by gxapplications** [comment]
Can we reopen this part?
In fact writeConfig has been deprecated on 1.6, so now to have a similar feature, you need to call writeCache from Driver part..

**Pull request merged**
