### PR TITLE
[fix] Broken build from version 1.5.3 to 1.5.5

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
#320

**Comment by robertsLando** [comment]
@ekarak  Please merge this one and release a new version one you can so I can release a stable version of Zwave2MQTT 1.3.0. I have successfully tested it and it compiles now

**Comment by milosjovac** [comment]
We tried this patch for fixing the issue https://github.com/OpenZWave/node-openzwave-shared/issues/322 and it works. 

Can you please share which sub-dependency made problems with a build?

**Comment by robertsLando** [comment]
@milosjovac There were 2 problems: first one it was using `ifdef` instead of `if` in C++ preprocessing. Than there was a problem with enum class. Check the tab here named "Files changed" for more info

**Comment by milosjovac** [comment]
@robertsLando tnx for the info. I was referring more to the reason of `openzwave-shared` not being buildable since ~2 weeks ago. Even with older versions it doesn't build at the moment (ex. 1.5.0), so it has to be that some of the dependencies have been changed. Do you know which one?

**Comment by robertsLando** [comment]
@milosjovac There was no problem with any deps, the problems was many, the first I had found was a typo on groups, than there was problems with bindings.gyp caused by ldconfig command than this one I think is the last one. Everything was caused by the updates to support OZW 1.6

**Comment by justinwalsh** [comment]
This fixed work for me! Confirmed builds are back and working on raspbian.

**Comment by cmanou** [comment]
This worked for me as well would be good to get a NPM release out with the fix

**Comment by ekarak** [comment]
version 1.5.6 just released on NPM

**Pull request merged**
