### PR TITLE
Osx compat

### PR DESCRIPTION
**Pull request by renz45**
This allows the module to be compiled on osx (10.8 and above).

The biggest changes are handling platform specific `unordered_map` and renaming `mutex` to `mutexx` to avoid a naming conflict in the stdlib on osx. I apologize if I did something terrible, this is really my first spelunking into c++. If anyone with more experience with c++ wants to make a few changes (or suggestions), feel free.

The test files work with these changes on el capitan.

### CODE REVIEW

**Comment by renz45** [comment]
Hmm.. I tried installing the module locally in a project later this evening and it doesn't seem to be honoring the `MACOSX_DEPLOYMENT_TARGET` option when being installed somewhere else (>_<)

**Comment by renz45** [comment]
Seems the issue is that 10.9 is required when being installed from another project (wat?). 

Here is the post that tipped me off to this whole `MACOSX_DEPLOYMENT_TARGET ` stuff : https://github.com/nodejs/node-gyp/issues/469

**Comment by renz45** [comment]
I started using this fork last night within an https://github.com/atom/electron project on my mac (el capitan osx10.11 and nodeJS 4.1.1) and was able to control a light switch and schlage door lock. I'm not seeing any issues so far. Thanks again for your work on this lib, it appears to be working great. :)

**Comment by ekarak** [comment]
Many many thanks for this! OS/X support was left behind and your contribution made me revisit some parts of the code that I haven't touched for ages.
I'm merging your work manually into a new branch which includes support for pushbuttons.
Could you please checkout the 'buttons' branch and try compiling it?

**Comment by renz45** [comment]
I'm getting the same error I got for the named maps:

```bash
 node-gyp rebuild

  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
In file included from ../src/callbacks.cc:18:
../src/openzwave.hpp:171:17: error: no member named 'tr1' in namespace 'std'
        typedef ::std::tr1::unordered_map <std::string, OpenZWave::Driver::ControllerCommand> CommandMap;
                ~~~~~~~^
../src/openzwave.hpp:171:36: error: expected unqualified-id
        typedef ::std::tr1::unordered_map <std::string, OpenZWave::Driver::ControllerCommand> CommandMap;
                                          ^
../src/openzwave.hpp:172:9: error: unknown type name 'CommandMap'
        extern CommandMap* ctrlCmdNames;
               ^
3 errors generated.
make: *** [Release/obj.target/openzwave_shared/src/callbacks.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adamrensel/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/adamrensel/.nvm/versions/node/v4.1.1/bin/node" "/Users/adamrensel/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adamrensel/Documents/projects/node-openzwave-shared
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/adamrensel/.nvm/versions/node/v4.1.1/bin/node" "/Users/adamrensel/.nvm/versions/node/v4.1.1/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! openzwave-shared@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adamrensel/Documents/projects/node-openzwave-shared/npm-debug.log
```

This was the commit that fixed it for me. I can look into the buttons branch a bit tonight if needed as well. I'm guessing the mutex name error will crop up again too without naming it something else :)

**Comment by renz45** [comment]
This was the mutex commit I was talking about: https://github.com/renz45/node-openzwave-shared/commit/b1f611f38854edf08f33b360caa9b2c9bbb2a430

mutexx was crappy naming on my part xD

**Comment by ekarak** [comment]
Please try again, I've fixed this declaration.

**Comment by renz45** [comment]
New error:

```bash
node-gyp rebuild

  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
../src/callbacks.cc:112:16: error: no viable overloaded '='
                notif->help  = new std::string();
                ~~~~~~~~~~~  ^ ~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1363:19: note:
      candidate function not viable: no known conversion from 'std::string *' (aka 'basic_string<char,
      char_traits<char>, allocator<char> > *') to 'const std::__1::basic_string<char>' for 1st argument; dereference
      the argument with *
    basic_string& operator=(const basic_string& __str);
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1366:19: note:
      candidate function not viable: no known conversion from 'std::string *' (aka 'basic_string<char,
      char_traits<char>, allocator<char> > *') to 'std::__1::basic_string<char>' for 1st argument; dereference the
      argument with *
    basic_string& operator=(basic_string&& __str)
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1370:45: note:
      candidate function not viable: no known conversion from 'std::string *' (aka 'basic_string<char,
      char_traits<char>, allocator<char> > *') to 'const value_type *' (aka 'const char *') for 1st argument
    _LIBCPP_INLINE_VISIBILITY basic_string& operator=(const value_type* __s) {return assign(__s);}
                                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1371:19: note:
      candidate function not viable: no known conversion from 'std::string *' (aka 'basic_string<char,
      char_traits<char>, allocator<char> > *') to 'value_type' (aka 'char') for 1st argument
    basic_string& operator=(value_type __c);
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:1374:19: note:
      candidate function not viable: no known conversion from 'std::string *' (aka 'basic_string<char,
      char_traits<char>, allocator<char> > *') to 'initializer_list<value_type>' for 1st argument
    basic_string& operator=(initializer_list<value_type> __il) {return assign(__il.begin(), __il.size());}
                  ^
../src/callbacks.cc:113:14: error: member reference type 'std::string' (aka 'basic_string<char, char_traits<char>,
      allocator<char> >') is not a pointer; maybe you meant to use '.'?
                notif->help->append(
                ~~~~~~~~~~~^~
                           .
2 errors generated.
make: *** [Release/obj.target/openzwave_shared/src/callbacks.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adamrensel/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/adamrensel/.nvm/versions/node/v4.1.1/bin/node" "/Users/adamrensel/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adamrensel/Documents/projects/node-openzwave-shared
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/adamrensel/.nvm/versions/node/v4.1.1/bin/node" "/Users/adamrensel/.nvm/versions/node/v4.1.1/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! openzwave-shared@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above
```

:(

**Comment by renz45** [comment]
On another note - my manual build of `open-zwave` refuses to link back up to this lib. If I install with homebrew (its an older version 1.2.x) then it goes back to working. It's a bit of a bummer, since 1.2 doesn't implement `addNode` which I was using the other night :(

**Comment by ekarak** [comment]
OK, fixed that too. That error is weird. I use a preprocessor directive (OPENZWAVE_SECURITY) to identify if the new Security API is present; in your case it wasn't. Is the ZWSecurity.h in your path? What's the output of
`pkg-config --cflags-only-I libopenzwave | sed s/-I//g`

Then, does the following return 0 or 1?
`find /path/returned/from/previous/command -name ZWSecurity.h | wc -l`

**Comment by renz45** [comment]
```
pkg-config --cflags-only-I libopenzwave | sed s/-I//g
Package libopenzwave was not found in the pkg-config search path.
Perhaps you should add the directory containing `libopenzwave.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libopenzwave' found

find /path/returned/from/previous/command -name ZWSecurity.h | wc -l
find: /path/returned/from/previous/command: No such file or directory
```

I did notice that the brew installed version doesn't have a libopenzwave.pc file like the manually built one did. Not sure if it has something to do with this: https://github.com/OpenZWave/open-zwave/issues/687

I've been trying to get the manual build to work, but no luck for some reason tonight :(

**Comment by ekarak** [comment]
ok I've pushed a fix which will enable you to compile and link against the old 1.2 OZW library. Please do a `git pull` on the buttons branch and try again. (sorry for this; no MacOS/X nearby)

**Comment by renz45** [comment]
No problem, happy to help! I only wish I knew more C++ so that I could offer a bit more help :)

2 this time :) 

Ran one, the commented out the offending line, then got another it almost finished compiling though.

First one: 

```bash
node-gyp rebuild

  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
../src/openzwave.cc:216:42: error: invalid operands to binary expression ('basic_ostream<char,
      std::__1::char_traits<char> >' and 'std::ostringstream' (aka 'basic_ostringstream<char>'))
                std::cout << "Initialising OpenZWave " << versionstream << " binary addon for Node.JS.\n";
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:207:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'const void *' for 1st argument; take the address of the argument with &
    basic_ostream& operator<<(const void* __p);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:191:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'std::__1::basic_ostream<char> &(*)(std::__1::basic_ostream<char> &)' for 1st argument
    basic_ostream& operator<<(basic_ostream& (*__pf)(basic_ostream&));
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:192:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'basic_ios<char_type, traits_type> &(*)(basic_ios<char_type, traits_type> &)' for 1st argument
    basic_ostream& operator<<(basic_ios<char_type, traits_type>&
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:194:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'std::__1::ios_base &(*)(std::__1::ios_base &)' for 1st argument
    basic_ostream& operator<<(ios_base& (*__pf)(ios_base&));
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:195:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'bool' for 1st argument
    basic_ostream& operator<<(bool __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:196:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'short' for 1st argument
    basic_ostream& operator<<(short __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:197:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'unsigned short' for 1st argument
    basic_ostream& operator<<(unsigned short __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:198:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'int' for 1st argument
    basic_ostream& operator<<(int __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:199:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'unsigned int' for 1st argument
    basic_ostream& operator<<(unsigned int __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:200:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'long' for 1st argument
    basic_ostream& operator<<(long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:201:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'unsigned long' for 1st argument
    basic_ostream& operator<<(unsigned long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:202:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'long long' for 1st argument
    basic_ostream& operator<<(long long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:203:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'unsigned long long' for 1st argument
    basic_ostream& operator<<(unsigned long long __n);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:204:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'float' for 1st argument
    basic_ostream& operator<<(float __f);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:205:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'double' for 1st argument
    basic_ostream& operator<<(double __f);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:206:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'long double' for 1st argument
    basic_ostream& operator<<(long double __f);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:208:20: note:
      candidate function not viable: no known conversion from 'std::ostringstream' (aka 'basic_ostringstream<char>')
      to 'basic_streambuf<char_type, traits_type> *' for 1st argument
    basic_ostream& operator<<(basic_streambuf<char_type, traits_type>* __sb);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:785:1: note:
      candidate function [with _CharT = char, _Traits = std::__1::char_traits<char>] not viable: no known conversion
      from 'std::ostringstream' (aka 'basic_ostringstream<char>') to 'char' for 2nd argument
operator<<(basic_ostream<_CharT, _Traits>& __os, char __cn)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:818:1: note:
      candidate function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from
      'std::ostringstream' (aka 'basic_ostringstream<char>') to 'char' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, char __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:825:1: note:
      candidate function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from
      'std::ostringstream' (aka 'basic_ostringstream<char>') to 'signed char' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, signed char __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:832:1: note:
      candidate function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from
      'std::ostringstream' (aka 'basic_ostringstream<char>') to 'unsigned char' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, unsigned char __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:846:1: note:
      candidate function [with _CharT = char, _Traits = std::__1::char_traits<char>] not viable: no known conversion
      from 'std::ostringstream' (aka 'basic_ostringstream<char>') to 'const char *' for 2nd argument
operator<<(basic_ostream<_CharT, _Traits>& __os, const char* __strn)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:892:1: note:
      candidate function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from
      'std::ostringstream' (aka 'basic_ostringstream<char>') to 'const char *' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, const char* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:899:1: note:
      candidate function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from
      'std::ostringstream' (aka 'basic_ostringstream<char>') to 'const signed char *' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, const signed char* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:907:1: note:
      candidate function [with _Traits = std::__1::char_traits<char>] not viable: no known conversion from
      'std::ostringstream' (aka 'basic_ostringstream<char>') to 'const unsigned char *' for 2nd argument
operator<<(basic_ostream<char, _Traits>& __os, const unsigned char* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1086:1: note:
      candidate function [with _CharT = char, _Traits = std::__1::char_traits<char>] not viable: no known conversion
      from 'std::ostringstream' (aka 'basic_ostringstream<char>') to 'const std::__1::error_code' for 2nd argument
operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __ec)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:778:1: note:
      candidate template ignored: deduced conflicting types for parameter '_CharT' ('char' vs.
      'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >')
operator<<(basic_ostream<_CharT, _Traits>& __os, _CharT __c)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1077:1: note:
      candidate template ignored: could not match 'basic_string' against 'basic_ostringstream'
operator<<(basic_ostream<_CharT, _Traits>& __os,
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1101:1: note:
      candidate template ignored: could not match 'bitset' against 'basic_ostringstream'
operator<<(basic_ostream<_CharT, _Traits>& __os, const bitset<_Size>& __x)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1063:5: note:
      candidate template ignored: disabled by 'enable_if' [with _Stream = std::__1::basic_ostream<char> &, _Tp =
      std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >]
    !is_lvalue_reference<_Stream>::value &&
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:839:1: note:
      candidate template ignored: could not match 'const _CharT *' against 'std::ostringstream'
      (aka 'basic_ostringstream<char>')
operator<<(basic_ostream<_CharT, _Traits>& __os, const _CharT* __str)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:1094:1: note:
      candidate template ignored: could not match 'shared_ptr' against 'basic_ostringstream'
operator<<(basic_ostream<_CharT, _Traits>& __os, shared_ptr<_Yp> const& __p)
^
1 error generated.
make: *** [Release/obj.target/openzwave_shared/src/openzwave.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adamrensel/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/adamrensel/.nvm/versions/node/v5.1.0/bin/node" "/Users/adamrensel/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adamrensel/Documents/projects/node-openzwave-shared
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm WARN EPACKAGEJSON openzwave-shared@1.1.4 license should be a valid SPDX license expression
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/adamrensel/.nvm/versions/node/v5.1.0/bin/node" "/Users/adamrensel/.nvm/versions/node/v5.1.0/bin/npm" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! openzwave-shared@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

So I commented out the line /src/openzwave.cc:216:42: `std::cout << "Initialising OpenZWave " << versionstream << " binary addon for Node.JS.\n";`

Then almost all the files finished compiling, but then stopped at: 

```bash
  CXX(target) Release/obj.target/openzwave_shared/src/utils.o
../src/utils.cc:310:10: error: member function 'GetAsString' not viable: 'this' argument has type
      'const OpenZWave::Notification', but function is not marked const
                return n->GetAsString();
                       ^
/usr/local/include/openzwave/Notification.h:182:10: note: 'GetAsString' declared here
                string GetAsString();
                       ^
1 error generated.
make: *** [Release/obj.target/openzwave_shared/src/utils.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adamrensel/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/adamrensel/.nvm/versions/node/v5.1.0/bin/node" "/Users/adamrensel/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adamrensel/Documents/projects/node-openzwave-shared
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by ekarak** [comment]
I have to go to work now, I'll update you later. Thanks!

**Comment by renz45** [comment]
I managed to get master working again for openzwave. I ended up deleting the repo and recloning and it magically started working. I need to figure out a good update flow that doesn't break everything.... wasted hours tonight on that.

**Comment by ekarak** [comment]
OK, that last error (function 'GetAsString' not viable) was an OpenZWave bug which I've raised OpenZWave#693 and got it approved and merged. 
I've also found, based on your symptoms, why my library wouldn't compile in the presence of multiple OpenZWave versions. I've pushed some patches in the 'buttons' branch to fix this.
Hope to have the 'buttons' branch (which includes your work) merged into master, once I validate it works on Windows too.

Many thanks again.

**Comment by renz45** [comment]
Made one comment here: 7203527

That fix makes the test.js work for me :)

**Comment by ekarak** [comment]
closing pull request - manually merged and released in 1.1.5

**Pull request closed without merging**
