### PR TITLE
Missing Method & Node group Notification & Value_Type List with corrected value concatenated

### PR DESCRIPTION
**Pull request by vibr77**

### CODE REVIEW

**Comment by vibr77** [comment]
Based on what I have seen value_list item value are integers

**Comment by ekarak** [comment]
I completely missed this PR! will try to merge this now...

**Comment by ekarak** [comment]
I merged your changes in https://github.com/OpenZWave/node-openzwave-shared/pull/304
I have no clue as to the typescript changes, can you please take a look?

**Comment by ekarak** [comment]
this can now be closed see #304

**Pull request closed without merging**
