### PR TITLE
Add support for building on Android

### PR DESCRIPTION
**Pull request by araczkowski**
Hi,
 we are able to compile and run open-zwave on Android:
https://github.com/OpenZWave/open-zwave/pull/2178

this will allow to compile node-openzwave-shared on Android

### CODE REVIEW

**Comment by ekarak** [comment]
seems that the Appveyor CI is failing because it uses Node 8 whereas some dependency is requiring Node 10... let me see if I can fix this for you

**Comment by ekarak** [comment]
lets see... 
https://ci.appveyor.com/project/ekarak/node-openzwave-shared/builds/32434666

**Comment by ekarak** [comment]
OK this seems to have worked, I'll now merge this into master and you will need to rebase.

**Comment by ekarak** [comment]
Ok done: https://github.com/OpenZWave/node-openzwave-shared/pull/373
please rebase your branch to include this change on appveyor.yaml

**Comment by araczkowski** [comment]
@ekarak let me know if we should improve something

The solution was tested on Android (see below), and in fact it is a copy & paste from "OS=='linux'"

```
$ pwd
/data/data/pl.sviete.dom/files/home/node-openzwave-shared
$ npm install

> openzwave-shared@1.6.2 preinstall /data/data/pl.sviete.dom/files/home/node-openzwave-shared
> node lib/install-ozw.js


> openzwave-shared@1.6.2 install /data/data/pl.sviete.dom/files/home/node-openzwave-shared
> node-gyp rebuild

make: Entering directory '/data/data/pl.sviete.dom/files/home/node-openzwave-shared/build'
  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-config.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-driver.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-groups.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-management.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-network.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-nodes.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-polling.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-scenes.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-values.o
  CXX(target) Release/obj.target/openzwave_shared/src/utils.o
  SOLINK_MODULE(target) Release/obj.target/openzwave_shared.node
clang-8: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
  COPY Release/openzwave_shared.node
make: Leaving directory '/data/data/pl.sviete.dom/files/home/node-openzwave-shared/build'
npm WARN openzwave-shared@1.6.2 license should be a valid SPDX license expression

audited 158 packages in 248.36s
found 0 vulnerabilities
```

**Comment by ekarak** [comment]
thank you Andrzej!

**Comment by araczkowski** [comment]
Thanks and have a good day!

BTW
now zwave2mqtt works on Android, my goal for today is done ;)

image

image

**Pull request merged**
